### PR TITLE
Use generic Task type in hints

### PR DESCRIPTION
**Pull request by nathanjmcdougall**
The motivation is just to get better type compliance. I rely on it pretty extensively in the editor.

There may be other places in this file to make similar changes in.  I'm doing this on mobile so I'm just trying to get the general idea in here.

### CODE REVIEW

**Comment by ben-denham** [comment]
Thanks for the PR @nathanjmcdougall 

I like the idea, but I've spotted a couple of issues:

1. The current code requires additional type-hinting in at least `TaskRunner.run()`, specifically I found that I had to:
   * Type hint `future_to_task` as `Dict[concurrent.futures.Future, TaskT]`
   * Use `future_to_task[future] = cast(TaskT, task)` to avoid generic type-hinting of `TaskState`
2. Even with those changes, the new type hinting doesn't support passing tasks of multiple types to `Lab.run_tasks()`. Specifically, mypy gives `Value of type variable "TaskT" of "run_tasks" of "Lab" cannot be "object"  [type-var]` for the following code:
   ```python
   import labtech


   @labtech.task
   class TaskA:

       def run(self):
           return 1


   @labtech.task
   class TaskB:

       def run(self):
           return 2


   tasks = [
       TaskA(),
       TaskB(),
   ]

   lab = labtech.Lab(storage=None)
   lab.run_tasks(tasks)
   ```

Any ideas to resolve these issues?

Another idea that could be interesting to think about along with this: Making `Task` generic in the return type of the `run()` method, so that `Task[pd.DataFrame]` (or a more specific Pandera type) would be valid.

**Comment by nathanjmcdougall** [comment]
Yeah with respect to point 1, as I say I'm on mobile so I won't have caught everything. I need to get on a Desktop and set up a dev environment to do this properly later this week unless you'd like to have a go in the meantime.

With respect to point 2, I will have to do some research...

**Comment by nathanjmcdougall** [comment]
On point 2, I think this may be a use-case for Variadic Generics (PEP 646). That would only be available in Python>=3.11 though.

**Comment by ben-denham** [comment]
@nathanjmcdougall

On point 1: I've made some more extensive changes on a separate branch that now pass mypy, feel free to add these to your pull request whenever you have a chance to review if you think they're appropriate to your typing needs: https://github.com/ben-denham/labtech/compare/main...type-hint-improvements

On point 2: It looks like variadic generics are for generics that have different types on different dimensions (e.g. columns in a dataframe), but it looks like the specific issue I spotted is resolved by type hinting the list of tasks. E.g.: `tasks: list[Task] = [ ... ]`.

**Comment by ben-denham** [comment]
I was able to simplify the type hinting a bit when I realised that `TaskState` shouldn't be generic in `TaskT`.

I'm merging in this PR now along with my other changes in an additional commit.

**Pull request merged**
